version: '3'
services:
  eddi:
    build:
      context: .
      args:
        EDDI_VERSION: 4.7
        EDDI_ENV: production
        EDDI_MEMORY_MIN: 128m
        EDDI_MEMORY_MAX: 128m
    image: labsai/eddi:local
    environment:
      EDDI_VERSION: 4.7
      EDDI_ENV: production
      EDDI_MEMORY_MIN: 128m
      EDDI_MEMORY_MAX: 128m
